# 阿里云服务器用
# 以后发布只需要执行如下内容

# 1 构建新版本
#  docker-compose build

# 2 启动并更新
#  docker-compose up -d

version: '3.8'

services:
  tangyuan-app:
    build: .
    container_name: tangyuan-app
    restart: always
    ports:
      - "54123:54123"
    volumes:
      - ./sqlite-data:/app/data  # 数据库持久化，永不丢失
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://*:54123