# 阿里云服务器用
# 只更新代码，那么只需要把发布后的文件上传到服务器上，执行如下内容
# cd /www/wwwroot/OpenTangYuanDocker
# docker-compose up -d --build


version: '3.8'

services:
  tangyuan-app:
    build: .
    container_name: tangyuan-app
    restart: always
    ports:
      - "54123:54123"
    volumes:
      - ./sqlite-data:/app/data  
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://*:54123